server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/phone_openers?autoReconnect=true
    username: spark
    password: flamerz801
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
    generate-ddl: true
    hibernate:
      ddl-auto: update